from pathlib import Path

import torch
import yaml
from sklearn.model_selection import train_test_split


def load_params():
    with open("params.yaml", "r") as file:
        params = yaml.safe_load(file)

    return params["preprocess"]


def standardize_images(images, mean, std):
    # Convert from [N, H, W, C] to [N, C, H, W]
    images = images.permute(0, 3, 1, 2).float()

    # Scale pixel values from [0, 255] to [0, 1]
    images = images / 255.0

    # Reshape mean and std for channel-wise standardization
    mean = torch.tensor(mean, dtype=torch.float32).view(1, 3, 1, 1)
    std = torch.tensor(std, dtype=torch.float32).view(1, 3, 1, 1)

    images = (images - mean) / std

    return images


def main():
    params = load_params()

    val_size = params["val_size"]
    seed = params["seed"]
    mean = params["mean"]
    std = params["std"]

    raw_dir = Path("data/raw")
    processed_dir = Path("data/processed")
    processed_dir.mkdir(parents=True, exist_ok=True)

    print("Loading raw CIFAR-10 data...")

    # These files were generated by prepare.py.
    # weights_only=False is safe here because these are our own local files.
    train_raw = torch.load(
        raw_dir / "train.pt",
        weights_only=False
    )

    test_raw = torch.load(
        raw_dir / "test.pt",
        weights_only=False
    )

    # Convert NumPy image arrays to tensors
    train_images = torch.from_numpy(train_raw["images"])
    train_labels = train_raw["labels"]

    test_images = torch.from_numpy(test_raw["images"])
    test_labels = test_raw["labels"]

    print("Normalizing and standardizing images...")

    train_images = standardize_images(train_images, mean, std)
    test_images = standardize_images(test_images, mean, std)

    # Create indices so images and labels remain aligned
    indices = list(range(len(train_labels)))

    train_indices, val_indices = train_test_split(
        indices,
        test_size=val_size,
        random_state=seed,
        stratify=train_labels.numpy()
    )

    train_indices = torch.tensor(train_indices, dtype=torch.long)
    val_indices = torch.tensor(val_indices, dtype=torch.long)

    processed_train = {
        "images": train_images[train_indices],
        "labels": train_labels[train_indices]
    }

    processed_val = {
        "images": train_images[val_indices],
        "labels": train_labels[val_indices]
    }

    processed_test = {
        "images": test_images,
        "labels": test_labels
    }

    print("Saving processed datasets...")

    torch.save(
        processed_train,
        processed_dir / "train.pt"
    )

    torch.save(
        processed_val,
        processed_dir / "val.pt"
    )

    torch.save(
        processed_test,
        processed_dir / "test.pt"
    )

    print("Preprocessing complete.")
    print(f"Training samples: {len(processed_train['labels'])}")
    print(f"Validation samples: {len(processed_val['labels'])}")
    print(f"Test samples: {len(processed_test['labels'])}")
    print(f"Processed data saved to: {processed_dir}")


if __name__ == "__main__":
    main()